######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 14 21:07:14 2010
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ..

# Input
HEADERS += ../HtmlConverter.h
SOURCES += HtmlConverterTest.cpp ../HtmlConverter.cpp
RESOURCES += ../TailViewResources.qrc
