######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 2 22:40:51 2010
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ..

# Input
HEADERS += HtmlConverterTest.h \
           MainWindowTest.h \
           TailViewTest.h \
           TestObject.h \
           TestRegister.h \
           ../HtmlConverter.h \
           ../TailView.h 
SOURCES += HtmlConverterTest.cpp \
           TailViewTest.cpp \
           testmain.cpp \
           TestObject.cpp \
           TestRegister.cpp \
           ../HtmlConverter.cpp \
           ../TailView.cpp
RESOURCES += UnitTestResources.qrc \
             ../TailViewResources.qrc 
