######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 14 21:07:14 2010
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ..

# Input
HEADERS += \
	HtmlConverterTest.h \
    TailViewTest.h \
	../HtmlConverter.h \
    ../TailView.h \

SOURCES += \
	HtmlConverterTest.cpp \
    TailViewTest.cpp \
	../HtmlConverter.cpp \
    ../TailView.cpp \
	testmain.cpp \

RESOURCES += \
	UnitTestResources.qrc \
	../TailViewResources.qrc \
